import type { Metadata } from "next";

import "./globals.css";
import Continer from "@/components/global/Continer";
import Navbar from "@/components/navbar/Navbar";

import Providers from "./Providers";
import { ClerkProvider } from '@clerk/nextjs';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
          <Continer className="py-20">{children}</Continer>
        </Providers>
      </body>
    </html>
    </ClerkProvider>
  );
}
